# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 19b8c7891c0bfed1663a95f01b69f69e6c06f69aee876f10106d9fb771765c05db0913b8ebb94d07b2a65a8bca840c0706a2c2f006f9a98543851da2497870b0

test:
  secret_key_base: 8e480555d1cad374f8db4a08c79b578b1049789f3e3f7d7c1f8fbcb7fe485f7b2ee778025084dd909e086bd4b462dd48bebe72bc5473cd4d07b67c7decdcd3b6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
